server:
  port: 8080

spring:
  application:
    name: CirculosEstudioBackend

  datasource:
    url: jdbc:postgresql://localhost:5432/Clubes
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect